metadata:
    name: 'Example Scanner #1.1.1'
    version: 0.5.3-alpha
    type: scanner
    author: Anonymous
    description: >
        An example scanner extension that does this and that.
        
        When the code is longer than 3 rows, it will automatically get truncated, which can be seen here with this example.

secrets:
    environment-variables:
        TEST: &e1 123

dependencies:
    apt:
        - tmux
    environment-variables:
        TEST: *e1